# Generated by Django 5.2.4 on 2025-08-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotacaoAvisoFerias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código da Lotação')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Lotação')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa para Aviso')),
            ],
            options={
                'verbose_name': 'Lotação para Aviso de Férias',
                'verbose_name_plural': 'Lotações para Aviso de Férias',
            },
        ),
        migrations.CreateModel(
            name='ServidorFerias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servidor', models.CharField(max_length=200, verbose_name='Nome do Servidor')),
                ('matricula', models.CharField(max_length=50, unique=True, verbose_name='Matrícula')),
                ('codigo_lotacao', models.CharField(max_length=10, verbose_name='Código da Lotação')),
                ('inicio_das_ferias', models.DateField(verbose_name='Início das Férias')),
                ('fim_das_ferias', models.DateField(verbose_name='Fim das Férias')),
                ('quantidade_dias_ferias', models.IntegerField(verbose_name='Quantidade de Dias')),
                ('competencia', models.CharField(max_length=7, verbose_name='Competência (YYYY-MM)')),
            ],
            options={
                'verbose_name': 'Servidor em Férias',
                'verbose_name_plural': 'Servidores em Férias',
                'unique_together': {('matricula', 'competencia')},
            },
        ),
    ]
